name = "M.A.E.S.T.R.O."
author = "encode42"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e26b3807a43a65bcc118534b53d0842e55dff213378979bd076a8a6ae2ab0820"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"
