name = "M.A.E.S.T.R.O."
author = "encode42"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a098c8c7fe8a2a47c179617985cd93c148477ac58b9113fdb8e50a3a182798d5"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"
